variable "project" {
  description = "Project slug."
  type        = string
}

variable "environment" {
  description = "Environment these secrets belong to."
  type        = string
}

variable "secrets" {
  description = "Map of short name to the JSON document stored under it, e.g. { docdb = jsonencode({...}) }. The full secret name becomes {project}/{environment}/{short name}."
  type        = map(string)
  sensitive   = true
}

variable "recovery_window_days" {
  description = "How long a deleted secret is recoverable. Zero, deliberately: with the default 30 days a destroyed environment leaves its secrets in a pending-deletion state where they still bill at $0.40/month each AND their names cannot be reused - so the next apply fails on a name that looks free. Recovery matters for a secret that took a human to produce; every secret here is regenerated by the next apply."
  type        = number
  default     = 0
}
